name: CI
run-name: ${{ github.sha }}
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  REPONAME: 'Test'
  SHA4: ${GITHUB_SHA:0:4}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      - name: Checkout
        uses: actions/checkout@v3
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world from https://test.com/${SHA4}.git
      - name: ls
        run: ls -lra
      - name: Render template
        id: render_template
        uses: chuhlomin/render-template@v1.6
        with:
          template: templates/template.yaml
          vars: |
            siteid: "tst5"

      - name: Deploy
        run: |-
          echo '${{ steps.render_template.outputs.result }}'
          
