name: Build pipeline services
on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Name the service to build'
        required: true
        default: '' 
        type: choice
        options:
        - rt-job-server
        - rt-job-worker
        - job-server
        - k8-agent
        - pipeline-state
        - file-converter
        - fs-sync
        - deid-preprocessor
        - pg-operations
env:
  SERVICE: ${{ github.event.inputs.services }}

jobs:
  test:
    name: "Build ${{ github.event.inputs.services }}"
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        run: |
            echo $DEV_ENV_FILE >> /tmp/credentials
            cat /tmp/credentials
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.SECRET1}}
          
      - name: print sbt command
        run:
          echo 'project $SERVICE / ${{ env.SERVICE }}'
      
      - name: Setup gcloud CLI with Docker auth
        # You may pin to the exact commit or the version.
        # uses: jacobsvante/setup-gcloud-with-docker-auth-action@b0bd90ddccb95eeca6a722ac5e93b8e32dad8da9
        uses: jacobsvante/setup-gcloud-with-docker-auth-action@v0.1.1
        with:
          # The Google Cloud JSON service account key to use for authentication
          gcp-credentials-json: ${{ secrets.DOCKER }}
          # The GCP project for which to set up gcloud CLI
          gcp-project-id: mendel-stage-001
