name: Build pipeline services
on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Name the service to build'
        required: true
        default: '' 
        type: choice
        options:
        - rt-job-server
        - rt-job-worker
        - job-server
        - k8-agent
        - pipeline-state
        - file-converter
        - fs-sync
        - deid-preprocessor
        - pg-operations
env:
  SERVICE: ${{ github.event.inputs.services }}

jobs:
  test:
    name: "Build ${{ github.event.inputs.services }}"
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        run: |
            echo $DEV_ENV_FILE >> /tmp/credentials
            cat /tmp/credentials
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.SECRET1}}
          
      - name: print sbt command
        run:
          echo 'project $SERVICE / ${{ env.SERVICE }}'

      - name: gcloud Container Registry Docker Login
        # You may pin to the exact commit or the version.
        # uses: elgohr/gcloud-login-action@ef736b239a2f47b76b0a58b688e9c603e65bb37a
        uses: elgohr/gcloud-login-action@v2
        with:
          # Base64 encoded service account key exported as JSON
          account_key: ${{ secrets.DOCKER }}
