name: Build rt-job-server
on:
  workflow_dispatch:

jobs:
  test:
    name: Build rt-job-server
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        run: |
            echo $DEV_ENV_FILE >> /tmp/credentials
            cat /tmp/credentials
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.SECRET1}}
      

      
      
