name: Build rt-job-server
on:
  workflow_dispatch:
    inputs:
      services:
        description: 'Name the service to build'
        required: true
        default: '' 
        type: choice
        options:
        - rt-job-server
        - rt-job-worker
        - job-server
        - k8-agent
        - pipeline-state
        - file-converter
        - fs-sync
        - deid-preprocessor
        - pg-operations
env:
  SERVICE: ${{ github.event.inputs.services }}

jobs:
  test:
    name: Build ${{ env.SERVICE }}
    runs-on: ubuntu-latest
    steps:
      - name: print secrets
        run: |
            echo $DEV_ENV_FILE >> /tmp/credentials
            cat /tmp/credentials
        shell: bash
        env:
          DEV_ENV_FILE : ${{secrets.SECRET1}}
      

      
      
